# Generated by Django 5.2.7 on 2025-11-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='latest',
            field=models.BooleanField(auto_created=True, default=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='staff_pick',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='trending',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
